#!/usr/bin/env bash

set -e
ROOTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"

cd "${ROOTDIR}"
source ${ROOTDIR}/tweaks/shell-functions

###############################################

banner dotbot

# This will download the dotbot script into the (submodule) dir "./dotbot"
try git submodule update --init --recursive

# Instruct dotbot to start ensuring symlinks + shell scripts are executed
try ./dotbot/bin/dotbot -c dotfiles.yaml "${@}"

banner "dotbot success"

say "press 'enter' to run all the tweaks/   or  '^c' to exit"
read -sp "waiting for input..." _x && echo

## run my scripts that prep my environment
try cd ${ROOTDIR}/tweaks
for a in *.sh; do

	banner ./${a}
	try ./${a}

done
