# RTFM:
# - https://starship.rs/config/#prompt
# - https://starship.rs/

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# https://starship.rs/advanced-config/#enable-right-prompt
format = """$character"""
# format = '''
# [┌ ](bold green)$directory
# [└─$character](bold green)'''


# right_format = """$all"""
right_format = """
$directory\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$c\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nodejs\
$ocaml\
$opa\
$pulumi\
$python\
$raku\
$rlang\
$rust\
$scala\
$swift\
$terraform\
$typst\
$zig\
$buf\
$conda\
$meson\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""


# I don't like the wasted top newline
add_newline = false

[aws]
disabled = true

[lua]
disabled = true

[package]
format = '[🎁 $version](208 bold) '
# disabled = true

[python]
disabled = false

[golang]
disabled = true

[time]
disabled = true

# [date]
# disabled = true

# [directory]
# truncation_length = 5
# truncate_to_repo = true

[kubernetes]
format = '[⎈ $context ](yellow)'
disabled = false

[kubernetes.context_aliases]
"foo" = "💚 dev"
"bar" = "⛔ prod"
"waz" = "♻️  tooling"
"baz" = "🌀 sandbox"

[gcloud]
disabled = true

[git_branch]
symbol = " "
truncation_length = 30
# truncation_symbol = ""
format = '[$symbol$branch(:$remote_branch)]($style) '

# [git_commit]


[git_status]
disabled = true
conflicted = "⚔️ "
# ahead = "🏎️ 💨 ×${count}"
behind = "🐢×${count}"
diverged = "🔱 🏎️ 💨 ×${ahead_count} 🐢 ×${behind_count}"
# untracked = "🛤️ ×${count} "
stashed = "📦 "
# modified = "📝×${count} "
staged = "🗃️  ×${count}"
renamed = "📛 ×${count}"
deleted = "🗑️  ×${count}"
style = "bright-white"
format = "$all_status$ahead_behind"

[git_commit]
commit_hash_length = 6
# tag_symbol = "ﰗ "
# tag_disabled = false
tag_symbol = "🏷 "


[nodejs]
disabled = true
# format = ""
#via [🤖 $version](bold green) "
# # format = "[ $symbol($version )]($style)"
